//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TP2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        public static byte[] _23_hyrule_castle_courtyard {
            get {
                object obj = ResourceManager.GetObject("_23_hyrule_castle_courtyard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        public static byte[] _41_potion_shop {
            get {
                object obj = ResourceManager.GetObject("_41_potion_shop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        public static byte[] _51_horse_race {
            get {
                object obj = ResourceManager.GetObject("_51_horse_race", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        public static byte[] _57_windmill_hut {
            get {
                object obj = ResourceManager.GetObject("_57_windmill_hut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1,pound,1,40,35,100,2
        ///2,karate-chop,2,50,25,100,2
        ///3,double-slap,1,15,10,85,2
        ///4,comet-punch,1,18,15,85,2
        ///5,mega-punch,1,80,20,85,2
        ///6,pay-day,1,40,20,100,2
        ///7,fire-punch,10,75,15,100,2
        ///8,ice-punch,15,75,15,100,2
        ///9,thunder-punch,13,75,15,100,2
        ///10,scratch,1,40,35,100,2
        ///11,vice-grip,1,55,30,100,2
        ///12,guillotine,1,,5,30,2
        ///13,razor-wind,1,80,10,100,3
        ///14,swords-dance,1,,20,,1
        ///15,cut,1,50,30,95,2
        ///16,gust,3,40,35,100,3
        ///17,wing-attack,3,60,35,100,2
        ///18,whirlwind,1,,20,,1
        ///19,fly,3,90,15,95,2
        ///20,bind,1,15,20,85,2
        ///21,slam,1 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string All_Attacks {
            get {
                return ResourceManager.GetString("All_Attacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1,Bulbasaur,45,49,49,65,65,45,64,45,4,8,3
        ///2,Ivysaur,60,62,63,80,80,60,142,45,4,8,3
        ///3,Venusaur,80,82,83,100,100,80,236,45,4,8,3
        ///4,Charmander,39,52,43,60,50,65,62,45,2,0,3
        ///5,Charmeleon,58,64,58,80,65,80,142,45,2,0,3
        ///6,Charizard,78,84,78,109,85,100,240,45,2,10,3
        ///7,Squirtle,44,48,65,50,64,43,63,45,3,0,3
        ///8,Wartortle,59,63,80,65,80,58,142,45,3,0,3
        ///9,Blastoise,79,83,100,85,105,78,239,45,3,0,3
        ///10,Caterpie,45,30,35,20,20,45,39,255,12,0,2
        ///11,Metapod,50,20,55,25,25,30,72,120,12,0,2
        ///12,Butterfree,60,45,50,90 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string All_Pokemon {
            get {
                return ResourceManager.GetString("All_Pokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bas1 {
            get {
                object obj = ResourceManager.GetObject("bas1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bas2 {
            get {
                object obj = ResourceManager.GetObject("bas2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bas3 {
            get {
                object obj = ResourceManager.GetObject("bas3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap droite1 {
            get {
                object obj = ResourceManager.GetObject("droite1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap droite2 {
            get {
                object obj = ResourceManager.GetObject("droite2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap footprints {
            get {
                object obj = ResourceManager.GetObject("footprints", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gauche1 {
            get {
                object obj = ResourceManager.GetObject("gauche1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gauche2 {
            get {
                object obj = ResourceManager.GetObject("gauche2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap haut1 {
            get {
                object obj = ResourceManager.GetObject("haut1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap haut2 {
            get {
                object obj = ResourceManager.GetObject("haut2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap haut3 {
            get {
                object obj = ResourceManager.GetObject("haut3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1,7,69
        ///2,10,130
        ///3,20,1000
        ///4,6,85
        ///5,11,190
        ///6,17,905
        ///7,5,90
        ///8,10,225
        ///9,16,855
        ///10,3,29
        ///11,7,99
        ///12,11,320
        ///13,3,32
        ///14,6,100
        ///15,10,295
        ///16,3,18
        ///17,11,300
        ///18,15,395
        ///19,3,35
        ///20,7,185
        ///21,3,20
        ///22,12,380
        ///23,20,69
        ///24,35,650
        ///25,4,60
        ///26,8,300
        ///27,6,120
        ///28,10,295
        ///29,4,70
        ///30,8,200
        ///31,13,600
        ///32,5,90
        ///33,9,195
        ///34,14,620
        ///35,6,75
        ///36,13,400
        ///37,6,99
        ///38,11,199
        ///39,5,55
        ///40,10,120
        ///41,8,75
        ///42,16,550
        ///43,5,54
        ///44,8,86
        ///45,12,186
        ///46,3,54
        ///47,10,295
        ///48,10,300
        ///49,15,125
        ///50,2,8
        ///51,7,333
        ///52,4,42
        ///53,10,320
        ///54,8,196
        ///55,17,766
        ///56,5,280
        ///57,10,320
        ///58, [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string height_weight {
            get {
                return ResourceManager.GetString("height_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
        ///jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
        ///jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
        ///jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
        ///jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
        ///jj [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap perso1_bas {
            get {
                object obj = ResourceManager.GetObject("perso1_bas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap perso1_droit {
            get {
                object obj = ResourceManager.GetObject("perso1_droit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap perso1_gauche {
            get {
                object obj = ResourceManager.GetObject("perso1_gauche", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap perso1_haut {
            get {
                object obj = ResourceManager.GetObject("perso1_haut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap perso2_bas {
            get {
                object obj = ResourceManager.GetObject("perso2_bas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap perso2_droit {
            get {
                object obj = ResourceManager.GetObject("perso2_droit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap perso2_gauche {
            get {
                object obj = ResourceManager.GetObject("perso2_gauche", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap perso2_haut {
            get {
                object obj = ResourceManager.GetObject("perso2_haut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pokemon {
            get {
                object obj = ResourceManager.GetObject("Pokemon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pokemon_Back {
            get {
                object obj = ResourceManager.GetObject("Pokemon_Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The seed on its back is filled with nutrients.The seed grows steadily larger as its body grows.
        ///Exposure to sunlight adds to its strength. Sunlight also makes the bud on its back grow larger.
        ///By spreading the broad petals of its flower and catching the sun&apos;s rays, it fills its body with power.
        ///The flame on its tail shows the strength of its life force. If it is weak, the flame also burns weakly.
        ///It is very hotheaded by nature, so it constantly seeks opponents. It calms down only when it wins.
        ///If CHARIZARD b [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Pokemon_Flavor_Text {
            get {
                return ResourceManager.GetString("Pokemon_Flavor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        public static byte[] Pokemon_GB {
            get {
                object obj = ResourceManager.GetObject("Pokemon_GB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1,Seed
        ///2,Seed
        ///3,Seed
        ///4,Lizard
        ///5,Flame
        ///6,Flame
        ///7,Tiny Turtle
        ///8,Turtle
        ///9,Shellfish
        ///10,Worm
        ///11,Cocoon
        ///12,Butterfly
        ///13,Hairy Bug
        ///14,Cocoon
        ///15,Poison Bee
        ///16,Tiny Bird
        ///17,Bird
        ///18,Bird
        ///19,Mouse
        ///20,Mouse
        ///21,Tiny Bird
        ///22,Beak
        ///23,Snake
        ///24,Cobra
        ///25,Mouse
        ///26,Mouse
        ///27,Mouse
        ///28,Mouse
        ///29,Poison Pin
        ///30,Poison Pin
        ///31,Drill
        ///32,Poison Pin
        ///33,Poison Pin
        ///34,Drill
        ///35,Fairy
        ///36,Fairy
        ///37,Fox
        ///38,Fox
        ///39,Balloon
        ///40,Balloon
        ///41,Bat
        ///42,Bat
        ///43,Weed
        ///44,Weed
        ///45,Flower
        ///46,Mushroom
        ///47,Mushroom
        ///48,Insect
        ///49,Poison Moth
        ///50,Mole
        ///51,Mole
        ///52,Scrat [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Pokemon_Species {
            get {
                return ResourceManager.GetString("Pokemon_Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tileset {
            get {
                object obj = ResourceManager.GetObject("Tileset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
